version: "3.5"
services:
  cuda:
    image: "cuda"
    container_name: cuda
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - "PUB_KEY=${PUB_KEY}"
      - "PRIVATE_KEY=${PRIVATE_KEY}"
    volumes:
      - cuda-sbt:/root/.sbt
      - cuda-ivy2:/root/.ivy2
      - cuda-cache:/root/.cache
      - cuda-m2:/root/.m2
      - cuda-vscode:/root/.vscode-server
      - .:/root/linzaddressparse
    ports:
      - 23:22
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  cuda-sbt:
  cuda-ivy2:
  cuda-cache:
  cuda-m2:
  cuda-vscode: